///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package utility.kafka.consumer;
//
//import org.junit.Test;
//import static org.junit.Assert.*;
//
//public class UtilityConsumerApplicationTest {
//    @Test public void testSomeLibraryMethod() {
//        UtilityConsumerApplication classUnderTest = new UtilityConsumerApplication();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//}
